import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync } from "node:fs";
import { createRequire } from "node:module";
import vm from "node:vm";
import ts from "typescript";
import { authenticateExternalProduct, ExternalProductConfigurationError } from "@/lib/external-capabilities/config";

// Generated by Live's actual core_message / ClaraCoreEvent.wire_payload at
// production f917529 (unchanged at 207ee8a), using synthetic project facts.
const fixture = JSON.parse(readFileSync(new URL("./live-work-cycle-event.fixture.json", import.meta.url), "utf8"));

function routeHarness(failDispatch = false) {
  const products = new Map([
    ["clara-live", { productId: "clara-live", workspaceId: "os-workspace", token: "test-credential", capabilities: [] }],
    ["other-product", { productId: "other-product", workspaceId: "other-os-workspace", token: "other-test-credential", capabilities: ["existing-grant"] }],
  ]);
  const received: Record<string, unknown>[] = [];
  const workspaces: string[] = [];
  const logs: Record<string, unknown>[] = [];
  const require = createRequire(import.meta.url);
  const modules: Record<string, unknown> = {
    "next/server": { NextResponse: Response },
    "@/lib/external-capabilities/config": { ExternalProductConfigurationError,
      authenticateExternalProduct: (id: string | null, auth: string | null) => authenticateExternalProduct(id, auth, products) },
    "@/lib/core/clara": { Clara: class { constructor(_key: string, workspace: string) { workspaces.push(workspace); } } },
    "@/lib/core/event-bus": { dispatchEvent: async (_clara: unknown, event: Record<string, unknown>) => {
      if (failDispatch) throw new Error("confidential-downstream-error");
      received.push(event); return { conversation: [], sources: [], state: "WORKING" };
    } },
    "@/lib/brain/response-composer": { composeClaraResponse: async () => "Contract accepted." },
    "@/lib/core/store/session-store": { saveSession: async () => {} },
    "@/lib/connectors/internal/openai/responses/openai-responses-engine": { OpenAIResponsesEngine: class {} },
    "@/types": { EventType: { USER_MESSAGE: "USER_MESSAGE", DOCUMENT_RECEIVED: "DOCUMENT_RECEIVED" } },
  };
  // Execute the actual route, substituting only downstream cognition/storage.
  // No production credentials, database, network or second validator copy.
  const source = readFileSync(new URL("../app/api/external/events/route.ts", import.meta.url), "utf8");
  const compiled = ts.transpileModule(source, { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022 } }).outputText;
  const exports: Record<string, unknown> = {};
  vm.runInNewContext(compiled, { exports, require: (name: string) => modules[name] ?? require(name),
    Response, crypto: globalThis.crypto, performance,
    console: { ...console, info: (_label: string, data: string) => logs.push(JSON.parse(data)) } });
  return { post: exports.POST as (request: Request) => Promise<Response>, received, workspaces, logs };
}

function request(body: unknown, credential = "test-credential", productId = "clara-live") {
  return new Request("https://os.example/api/external/events", { method: "POST",
    headers: { Authorization: `Bearer ${credential}`, "x-clara-product": productId, "Content-Type": "application/json" },
    body: JSON.stringify(body) });
}

test("actual Live Work Cycle payload reaches Core with project identity preserved", async () => {
  const route = routeHarness();
  assert.ok(fixture.message.includes("/"));
  const response = await route.post(request(fixture));
  assert.equal(response.status, 200);
  assert.equal((await response.json()).data.sessionId, fixture.scope.sessionId);
  assert.deepEqual(route.workspaces, ["os-workspace"]);
  assert.equal(route.received[0].type, "USER_MESSAGE");
  const context = route.received[0].context as Record<string, unknown>;
  for (const key of ["productId", "workspaceId", "userId", "sessionId"]) assert.equal(context[key], fixture.scope[key]);
});

test("slashes and JSON backslashes are valid text, never valid scope identifiers", async () => {
  const route = routeHarness();
  assert.equal((await route.post(request({ ...fixture, message: 'L / R; C:\\sources; {"value":"line\\nnext"}' }))).status, 200);
  for (const key of ["productId", "workspaceId", "userId", "sessionId"]) {
    assert.equal((await route.post(request({ ...fixture, scope: { ...fixture.scope, [key]: "unsafe/id" } }))).status, 400);
  }
});

test("malformed event bodies and invalid messages are explicitly refused", async () => {
  const route = routeHarness();
  for (const message of [undefined, null, 123, {}, "", "  ", "nul\0text", "x".repeat(100001)]) {
    const response = await route.post(request({ ...fixture, message }));
    assert.equal(response.status, 400);
    assert.equal((await response.json()).error, "Invalid Clara Core event.");
  }
  for (const body of [null, [], { ...fixture, schemaVersion: "invalid" }, { ...fixture, scope: {} }]) {
    assert.equal((await route.post(request(body))).status, 400);
  }
  const invalidJson = request(fixture);
  const response = await route.post(new Request(invalidJson.url, { method: "POST", headers: invalidJson.headers, body: "not-json" }));
  assert.equal(response.status, 400);
  assert.equal((await response.json()).error, "Invalid JSON request body.");
  assert.equal(route.received.length, 0);
});

test("authentication precedes event validation and other product isolation is unchanged", async () => {
  const route = routeHarness();
  assert.equal((await route.post(request(fixture, "incorrect"))).status, 401);
  assert.equal((await route.post(request({}, "incorrect"))).status, 401);
  assert.equal((await route.post(request(fixture, "other-test-credential", "other-product"))).status, 403);
  const other = { ...fixture, scope: { ...fixture.scope, productId: "other-product" } };
  assert.equal((await route.post(request(other, "other-test-credential", "other-product"))).status, 200);
  assert.deepEqual(route.workspaces, ["other-os-workspace"]);
});

test("correlated phase logs preserve status and exclude credentials and message contents", async () => {
  const route = routeHarness();
  const req = request({ ...fixture, message: "confidential-project-content" });
  req.headers.set("x-clara-correlation-id", "a".repeat(32));
  assert.equal((await route.post(req)).status, 200);
  assert.ok(route.logs.every((row) => row.correlation_id === "a".repeat(32)));
  for (const phase of ["authentication", "body_validation", "core_dispatch", "response_composition", "document_analysis", "session_persistence"]) {
    assert.ok(route.logs.some((row) => row.phase === phase && row.event === "phase_end" && typeof row.duration_ms === "number"));
  }
  assert.equal(route.logs.at(-1)?.http_status, 200);
  const serialized = JSON.stringify(route.logs);
  assert.ok(!serialized.includes("test-credential"));
  assert.ok(!serialized.includes("confidential-project-content"));
});

test("untrusted correlation headers are replaced and auth failures remain observable", async () => {
  const route = routeHarness();
  const req = request(fixture, "incorrect");
  req.headers.set("x-clara-correlation-id", "untrusted-private-value");
  assert.equal((await route.post(req)).status, 401);
  assert.match(String(route.logs[0].correlation_id), /^[a-f0-9]{32}$/);
  assert.equal(route.logs.at(-1)?.http_status, 401);
  assert.ok(!JSON.stringify(route.logs).includes("untrusted-private-value"));
});

test("Core failures identify the failed phase and real 500 without logging exception contents", async () => {
  const route = routeHarness(true);
  assert.equal((await route.post(request(fixture))).status, 500);
  assert.equal(route.logs.at(-1)?.phase, "core_dispatch");
  assert.equal(route.logs.at(-1)?.http_status, 500);
  assert.equal(route.logs.at(-1)?.outcome, "rejected_or_failed");
  assert.ok(!JSON.stringify(route.logs).includes("confidential-downstream-error"));
});
