import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync } from "node:fs";
import { createRequire } from "node:module";
import { documentOperations, operationScopeKey, operationFingerprint, type DocumentOperation } from "@/lib/external-capabilities/document-operations";
import vm from "node:vm";
import ts from "typescript";
import { authenticateExternalProduct, ExternalProductConfigurationError } from "@/lib/external-capabilities/config";

// Generated by Live's actual core_message / ClaraCoreEvent.wire_payload at
// production f917529 (unchanged at 207ee8a), using synthetic project facts.
const fixture = JSON.parse(readFileSync(new URL("./live-work-cycle-event.fixture.json", import.meta.url), "utf8"));

function routeHarness(failDispatch = false, store = documentOperations, failSession = false) {
  const products = new Map([
    ["clara-live", { productId: "clara-live", workspaceId: "os-workspace", token: "test-credential", capabilities: [] }],
    ["other-product", { productId: "other-product", workspaceId: "other-os-workspace", token: "other-test-credential", capabilities: ["existing-grant"] }],
  ]);
  const received: Record<string, unknown>[] = [];
  const workspaces: string[] = [];
  const logs: Record<string, unknown>[] = [];
  const require = createRequire(import.meta.url);
  const modules: Record<string, unknown> = {
    "@/lib/external-capabilities/document-operations": { documentOperations: store, operationScopeKey, operationFingerprint },
    "next/server": { NextResponse: Response },
    "@/lib/external-capabilities/config": { ExternalProductConfigurationError,
      authenticateExternalProduct: (id: string | null, auth: string | null) => authenticateExternalProduct(id, auth, products) },
    "@/lib/core/clara": { Clara: class { constructor(_key: string, workspace: string) { workspaces.push(workspace); } } },
    "@/lib/core/event-bus": { dispatchEvent: async (_clara: unknown, event: Record<string, unknown>) => {
      if (failDispatch) throw new Error("confidential-downstream-error");
      received.push(event); return { conversation: [], sources: [], state: "WORKING" };
    } },
    "@/lib/brain/response-composer": { composeClaraResponse: async () => "Contract accepted." },
    "@/lib/core/store/session-store": { saveSession: async () => { if (failSession) throw new Error("private-storage-error"); } },
    "@/lib/connectors/internal/openai/responses/openai-responses-engine": { OpenAIResponsesEngine: class { async generate() { return { success: true, content: JSON.stringify({ entities: [], facts: [], ambiguities: [], conflicts: [] }) }; } } },
    "@/types": { EventType: { USER_MESSAGE: "USER_MESSAGE", DOCUMENT_RECEIVED: "DOCUMENT_RECEIVED" } },
  };
  // Execute the actual route, substituting only downstream cognition/storage.
  // No production credentials, database, network or second validator copy.
  const source = readFileSync(new URL("../app/api/external/events/route.ts", import.meta.url), "utf8");
  const compiled = ts.transpileModule(source, { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022 } }).outputText;
  const exports: Record<string, unknown> = {};
  vm.runInNewContext(compiled, { exports, require: (name: string) => modules[name] ?? require(name),
    Response, crypto: globalThis.crypto, performance, process: { env: {} },
    console: { ...console, info: (_label: string, data: string) => logs.push(JSON.parse(data)) } });
  const statusSource = readFileSync(new URL("../app/api/external/document-operations/status/route.ts", import.meta.url), "utf8");
  const statusExports: Record<string, unknown> = {};
  vm.runInNewContext(ts.transpileModule(statusSource, { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022 } }).outputText,
    { exports: statusExports, require: (name: string) => modules[name] ?? require(name) });
  return { post: exports.POST as (request: Request) => Promise<Response>,
    statusPost: statusExports.POST as (request: Request) => Promise<Response>, received, workspaces, logs };
}

function request(body: unknown, credential = "test-credential", productId = "clara-live") {
  return new Request("https://os.example/api/external/events", { method: "POST",
    headers: { Authorization: `Bearer ${credential}`, "x-clara-product": productId, "Content-Type": "application/json" },
    body: JSON.stringify(body) });
}

test("actual Live Work Cycle payload reaches Core with project identity preserved", async () => {
  const route = routeHarness();
  assert.ok(fixture.message.includes("/"));
  const response = await route.post(request(fixture));
  assert.equal(response.status, 200);
  assert.equal((await response.json()).data.sessionId, fixture.scope.sessionId);
  assert.deepEqual(route.workspaces, ["os-workspace"]);
  assert.equal(route.received[0].type, "USER_MESSAGE");
  const context = route.received[0].context as Record<string, unknown>;
  for (const key of ["productId", "workspaceId", "userId", "sessionId"]) assert.equal(context[key], fixture.scope[key]);
});

test("slashes and JSON backslashes are valid text, never valid scope identifiers", async () => {
  const route = routeHarness();
  assert.equal((await route.post(request({ ...fixture, message: 'L / R; C:\\sources; {"value":"line\\nnext"}' }))).status, 200);
  for (const key of ["productId", "workspaceId", "userId", "sessionId"]) {
    assert.equal((await route.post(request({ ...fixture, scope: { ...fixture.scope, [key]: "unsafe/id" } }))).status, 400);
  }
});

test("malformed event bodies and invalid messages are explicitly refused", async () => {
  const route = routeHarness();
  for (const message of [undefined, null, 123, {}, "", "  ", "nul\0text", "x".repeat(100001)]) {
    const response = await route.post(request({ ...fixture, message }));
    assert.equal(response.status, 400);
    assert.equal((await response.json()).error, "Invalid Clara Core event.");
  }
  for (const body of [null, [], { ...fixture, schemaVersion: "invalid" }, { ...fixture, scope: {} }]) {
    assert.equal((await route.post(request(body))).status, 400);
  }
  const invalidJson = request(fixture);
  const response = await route.post(new Request(invalidJson.url, { method: "POST", headers: invalidJson.headers, body: "not-json" }));
  assert.equal(response.status, 400);
  assert.equal((await response.json()).error, "Invalid JSON request body.");
  assert.equal(route.received.length, 0);
});

test("authentication precedes event validation and other product isolation is unchanged", async () => {
  const route = routeHarness();
  assert.equal((await route.post(request(fixture, "incorrect"))).status, 401);
  assert.equal((await route.post(request({}, "incorrect"))).status, 401);
  assert.equal((await route.post(request(fixture, "other-test-credential", "other-product"))).status, 403);
  const other = { ...fixture, scope: { ...fixture.scope, productId: "other-product" } };
  assert.equal((await route.post(request(other, "other-test-credential", "other-product"))).status, 200);
  assert.deepEqual(route.workspaces, ["other-os-workspace"]);
});

test("correlated phase logs preserve status and exclude credentials and message contents", async () => {
  const route = routeHarness();
  const req = request({ ...fixture, message: "confidential-project-content" });
  req.headers.set("x-clara-correlation-id", "a".repeat(32));
  assert.equal((await route.post(req)).status, 200);
  assert.ok(route.logs.every((row) => row.correlation_id === "a".repeat(32)));
  for (const phase of ["authentication", "body_validation", "core_dispatch", "response_composition", "document_analysis", "session_persistence"]) {
    assert.ok(route.logs.some((row) => row.phase === phase && row.event === "phase_end" && typeof row.duration_ms === "number"));
  }
  assert.equal(route.logs.at(-1)?.http_status, 200);
  const serialized = JSON.stringify(route.logs);
  assert.ok(!serialized.includes("test-credential"));
  assert.ok(!serialized.includes("confidential-project-content"));
});

test("untrusted correlation headers are replaced and auth failures remain observable", async () => {
  const route = routeHarness();
  const req = request(fixture, "incorrect");
  req.headers.set("x-clara-correlation-id", "untrusted-private-value");
  assert.equal((await route.post(req)).status, 401);
  assert.match(String(route.logs[0].correlation_id), /^[a-f0-9]{32}$/);
  assert.equal(route.logs.at(-1)?.http_status, 401);
  assert.ok(!JSON.stringify(route.logs).includes("untrusted-private-value"));
});

test("Core failures identify the failed phase and real 500 without logging exception contents", async () => {
  const route = routeHarness(true);
  assert.equal((await route.post(request(fixture))).status, 500);
  assert.equal(route.logs.at(-1)?.phase, "core_dispatch");
  assert.equal(route.logs.at(-1)?.http_status, 500);
  assert.equal(route.logs.at(-1)?.outcome, "rejected_or_failed");
  assert.ok(!JSON.stringify(route.logs).includes("confidential-downstream-error"));
});

function memoryRegistry() {
  const rows = new Map<string, DocumentOperation>();
  return {
    rows,
    async lookup(scope: string, id: string) { return rows.get(scope + id) ?? null; },
    async reserve(scope: string, id: string, fingerprint: string) {
      const key = scope + id;
      if (rows.has(key)) return { owned: false, operation: rows.get(key) };
      const operation: DocumentOperation = { scope_key: scope, operation_id: id, fingerprint, owner_token: crypto.randomUUID(), status: "processing", result: null };
      rows.set(key, operation);
      return { owned: true, operation };
    },
    async complete(operation: DocumentOperation, result: Record<string, unknown>) { operation.status = "completed"; operation.result = result; },
    async fail(operation: DocumentOperation) { if (operation.status !== "completed") operation.status = "failed"; },
  };
}
// Generated from Live's real DOCUMENT_INSTRUCTION, source_segments and wire_payload.
const docEvent = JSON.parse(readFileSync(new URL("./live-document-operation.fixture.json", import.meta.url), "utf8"));

test("durable documentary calls reserve once under concurrency and recover the stored result", async () => {
  const store = memoryRegistry();
  const route = routeHarness(false, store);
  const responses = await Promise.all(Array.from({ length: 10 }, () => route.post(request(docEvent))));
  assert.equal(route.received.length, 1);
  assert.ok(responses.every((response) => [200, 202].includes(response.status)));
  const response = await route.statusPost(request({ operationId: docEvent.operationId, scope: docEvent.scope }));
  assert.equal(response.status, 200);
  const data = (await response.json()).data;
  assert.equal(data.status, "completed");
  assert.equal(data.result.sessionId, docEvent.scope.sessionId);
  assert.equal(data.result.structuredResult.documentAnalysis.schemaVersion, "clara.document-analysis.v1");
  assert.equal((await route.post(request(docEvent))).status, 200);
  assert.equal(route.received.length, 1);
  assert.ok(!JSON.stringify(route.logs).includes("synthetic confidential content"));
});

test("operation IDs conflict on changed payload and status access is scoped and authenticated", async () => {
  const route = routeHarness(false, memoryRegistry());
  assert.equal((await route.post(request(docEvent))).status, 200);
  const conflict = await route.post(request({ ...docEvent, message: "different instruction" }));
  assert.equal(conflict.status, 409);
  assert.equal((await conflict.json()).code, "DOCUMENT_OPERATION_CONFLICT");
  assert.equal((await route.statusPost(request({}, "wrong"))).status, 401);
  for (const key of ["workspaceId", "userId", "sessionId"]) {
    assert.equal((await route.statusPost(request({ operationId: docEvent.operationId,
      scope: { ...docEvent.scope, [key]: "other" } }))).status, 404);
  }
  assert.equal((await route.statusPost(request({ operationId: docEvent.operationId, scope: docEvent.scope },
    "other-test-credential", "other-product"))).status, 403);
  const other = { ...docEvent.scope, productId: "other-product" };
  assert.equal((await route.statusPost(request({ operationId: docEvent.operationId, scope: other },
    "other-test-credential", "other-product"))).status, 404);
  assert.equal(route.received.length, 1);
});

test("a crash never authorizes another analysis and session failure cannot erase the completed document result", async () => {
  const failedStore = memoryRegistry();
  const failed = routeHarness(true, failedStore);
  assert.equal((await failed.post(request(docEvent))).status, 500);
  assert.equal((await failed.post(request(docEvent))).status, 202);
  assert.equal((await (await failed.statusPost(request({ operationId: docEvent.operationId, scope: docEvent.scope }))).json()).data.status, "failed");
  const route = routeHarness(false, memoryRegistry(), true);
  assert.equal((await route.post(request(docEvent))).status, 500);
  const recovered = await route.statusPost(request({ operationId: docEvent.operationId, scope: docEvent.scope }));
  assert.equal((await recovered.json()).data.status, "completed");
  assert.equal((await route.post(request(docEvent))).status, 200);
  assert.equal(route.received.length, 1);
});

test("new registry fails closed while legacy consumers do not require its migration", async () => {
  const store = memoryRegistry();
  store.reserve = async () => { throw new Error("private database configuration"); };
  const route = routeHarness(false, store);
  assert.equal((await route.post(request(docEvent))).status, 503);
  assert.equal(route.received.length, 0);
  assert.equal((await route.post(request(fixture))).status, 200);
  for (const operationId of ["bad", 12, null]) assert.equal((await route.post(request({ ...docEvent, operationId }))).status, 400);
  assert.equal((await route.post(request({ ...fixture, operationId: docEvent.operationId }))).status, 400);
});
