import { NextResponse } from "next/server";
import { ConnectionStatus, type Connection } from "@/lib/connections/connection";
import { DatabaseConnectionRepository } from "@/lib/connections/connection-repository";
import { CredentialStore } from "@/lib/connections/credential-store";
import { CURRENT_WORKSPACE_ID } from "@/lib/connections/current-workspace";
import type { MakeWebhookCredentials } from "@/lib/connectors/make";
type ConfigureMakeRequest = { scenarioKey?: unknown; webhookUrl?: unknown };
const PRIVATE_HEADERS = { "Cache-Control": "private, no-store" }; const MAX_SCENARIOS = 100; const MAX_HEADERS = 32; const MAX_BODY_BYTES = 4096; const HEADER_NAME = /^[!#$%&'*+.^_`|~0-9A-Za-z-]{1,128}$/; const SCENARIO_FIELDS = new Set(["url", "headers", "timeoutMs"]); const REQUEST_FIELDS = new Set(["scenarioKey", "webhookUrl"]);
function validScenarioKey(value: unknown): value is string { return typeof value === "string" && /^[a-zA-Z0-9._:-]{1,120}$/.test(value.trim()); }
function isMakeWebhookHost(hostname: string): boolean { const host = hostname.toLowerCase(); return host === "make.com" || host.endsWith(".make.com") || host === "integromat.com" || host.endsWith(".integromat.com"); }
function normalizeWebhookUrl(value: unknown): string | null { if (typeof value !== "string") return null; const candidate = value.trim(); if (!candidate || candidate.length > 2048) return null; try { const url = new URL(candidate); if (url.protocol !== "https:" || url.username || url.password || url.hash || url.search || !isMakeWebhookHost(url.hostname) || url.pathname.length <= 1) return null; return url.toString(); } catch { return null; } }
function validOptions(scenario: Record<string, unknown>): boolean { if (Object.keys(scenario).some((key) => !SCENARIO_FIELDS.has(key))) return false; if (scenario.headers !== undefined) { if (!scenario.headers || typeof scenario.headers !== "object" || Array.isArray(scenario.headers)) return false; const entries = Object.entries(scenario.headers); if (entries.length > MAX_HEADERS || entries.some(([name, value]) => !HEADER_NAME.test(name) || typeof value !== "string" || value.length > 4096 || /[\r\n]/.test(value))) return false; } return scenario.timeoutMs === undefined || (typeof scenario.timeoutMs === "number" && Number.isFinite(scenario.timeoutMs) && scenario.timeoutMs >= 1_000 && scenario.timeoutMs <= 39_000); }
function scenarioMap(value: MakeWebhookCredentials | null): MakeWebhookCredentials["scenarios"] { if (!value || typeof value.scenarios !== "object" || value.scenarios === null || Array.isArray(value.scenarios)) return {}; const scenarios: MakeWebhookCredentials["scenarios"] = {}; for (const [key, scenario] of Object.entries(value.scenarios)) { const url = scenario && typeof scenario === "object" ? normalizeWebhookUrl(scenario.url) : null; if (!validScenarioKey(key) || !url || !validOptions(scenario as unknown as Record<string, unknown>)) continue; scenarios[key] = { url, ...(scenario.headers ? { headers: scenario.headers } : {}), ...(scenario.timeoutMs !== undefined ? { timeoutMs: scenario.timeoutMs } : {}) }; } return scenarios; }
export async function POST(request: Request) {
  if (!request.headers.get("content-type")?.toLowerCase().startsWith("application/json")) return NextResponse.json({ error: "UNSUPPORTED_MEDIA_TYPE" }, { status: 415, headers: PRIVATE_HEADERS });
  let body: ConfigureMakeRequest; try { const text = await request.text(); if (new TextEncoder().encode(text).length > MAX_BODY_BYTES) return NextResponse.json({ error: "REQUEST_TOO_LARGE" }, { status: 413, headers: PRIVATE_HEADERS }); const parsed: unknown = JSON.parse(text); if (!parsed || typeof parsed !== "object" || Array.isArray(parsed) || Object.keys(parsed).length !== 2 || Object.keys(parsed).some((key) => !REQUEST_FIELDS.has(key))) return NextResponse.json({ error: "INVALID_REQUEST" }, { status: 400, headers: PRIVATE_HEADERS }); body = parsed as ConfigureMakeRequest; } catch { return NextResponse.json({ error: "INVALID_REQUEST" }, { status: 400, headers: PRIVATE_HEADERS }); }
  const webhookUrl = normalizeWebhookUrl(body.webhookUrl); if (!validScenarioKey(body.scenarioKey) || !webhookUrl) return NextResponse.json({ error: "INVALID_CONFIGURATION" }, { status: 400, headers: PRIVATE_HEADERS }); const scenarioKey = body.scenarioKey.trim();
  try {
    const repository = new DatabaseConnectionRepository(); const credentialStore = new CredentialStore(); const existing = await repository.findByWorkspaceAndProvider(CURRENT_WORKSPACE_ID, "make"); const now = new Date(); const connection: Connection = existing ?? { id: crypto.randomUUID(), workspaceId: CURRENT_WORKSPACE_ID, provider: "make", status: ConnectionStatus.CONFIGURED, scopes: [], createdAt: now, updatedAt: now };
    const previousCredentials = existing ? await credentialStore.get<MakeWebhookCredentials>(connection.id) : null; if (existing && (!previousCredentials || Object.keys(previousCredentials as unknown as Record<string, unknown>).some((key) => key !== "scenarios"))) { await repository.updateStatus(connection.id, ConnectionStatus.RECONNECT_REQUIRED).catch(() => undefined); return NextResponse.json({ error: "EXISTING_CREDENTIALS_UNAVAILABLE" }, { status: 409, headers: PRIVATE_HEADERS }); }
    const rawScenarios = previousCredentials?.scenarios; if (existing && (typeof rawScenarios !== "object" || rawScenarios === null || Array.isArray(rawScenarios))) { await repository.updateStatus(connection.id, ConnectionStatus.RECONNECT_REQUIRED).catch(() => undefined); return NextResponse.json({ error: "EXISTING_CONFIGURATION_INVALID" }, { status: 409, headers: PRIVATE_HEADERS }); }
    const previousScenarios = scenarioMap(previousCredentials); if (existing && rawScenarios && Object.keys(rawScenarios).length !== Object.keys(previousScenarios).length) { await repository.updateStatus(connection.id, ConnectionStatus.RECONNECT_REQUIRED).catch(() => undefined); return NextResponse.json({ error: "EXISTING_CONFIGURATION_INVALID" }, { status: 409, headers: PRIVATE_HEADERS }); }
    if (!(scenarioKey in previousScenarios) && Object.keys(previousScenarios).length >= MAX_SCENARIOS) return NextResponse.json({ error: "SCENARIO_LIMIT_REACHED" }, { status: 409, headers: PRIVATE_HEADERS }); const previousScenario = previousScenarios[scenarioKey]; const credentials: MakeWebhookCredentials = { scenarios: { ...previousScenarios, [scenarioKey]: { ...(previousScenario?.headers ? { headers: previousScenario.headers } : {}), ...(previousScenario?.timeoutMs !== undefined ? { timeoutMs: previousScenario.timeoutMs } : {}), url: webhookUrl } } }; const scopes = new Set(connection.scopes.filter((scope) => !scope.startsWith("make:scenario:"))); for (const key of Object.keys(credentials.scenarios)) scopes.add(`make:scenario:${key}`);
    await credentialStore.set(connection.id, credentials); try { await repository.save({ ...connection, status: ConnectionStatus.CONFIGURED, scopes: [...scopes], updatedAt: now }); } catch (error) { if (existing && previousCredentials) await credentialStore.set(connection.id, previousCredentials).catch(() => undefined); throw error; }
    return NextResponse.json({ provider: "make", connected: false, status: ConnectionStatus.CONFIGURED, scenarioKey }, { headers: PRIVATE_HEADERS });
  } catch { return NextResponse.json({ error: "CONFIGURATION_UNAVAILABLE" }, { status: 503, headers: PRIVATE_HEADERS }); }
}
